export const ROLES = Object.freeze({
  ADMIN: 'admin',
  SUPERVISOR: 'supervisor',
});

const BOTH = [ROLES.ADMIN, ROLES.SUPERVISOR];
const ADMIN_ONLY = [ROLES.ADMIN];

const standardModule = { CREATE: BOTH, READ: BOTH, UPDATE: BOTH, DELETE: ADMIN_ONLY, RESTORE: ADMIN_ONLY };

export const PERMISSIONS = Object.freeze({
  VEHICLE: standardModule,
  MACHINERY: standardModule,
  MAINTENANCE: standardModule,
  SERVICE: standardModule,
  TYRE: standardModule,
  FUEL: standardModule,
  COMPLIANCE: standardModule,
  SITE: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY, ASSIGN: ADMIN_ONLY },
  DOCUMENT: { CREATE: BOTH, READ: BOTH },

  ITEM_CATEGORY: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY },
  UOM: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY },
  ITEM: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY },
  SUPPLIER: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY },
  STORAGE_LOCATION: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY },

  PURCHASE: { CREATE: BOTH, READ: BOTH, UPDATE: BOTH, RECEIVE: BOTH },
  STOCK: { READ: BOTH },

  ASSET_ISSUE: { CREATE: BOTH, READ: BOTH, REVERSE: BOTH },

  STOCK_ADJUSTMENT: { CREATE: BOTH, READ: BOTH },
  STOCK_TRANSFER: { CREATE: ADMIN_ONLY, READ: ADMIN_ONLY, RECEIVE: ADMIN_ONLY },

  FUEL_STATION: { ...standardModule, CREATE: ADMIN_ONLY, UPDATE: ADMIN_ONLY },
  FUEL_COLLECTION: { CREATE: BOTH, READ: BOTH, UPDATE: BOTH, RECEIVE: BOTH, CANCEL: ADMIN_ONLY },
  FUEL_STOCK: { READ: BOTH },

  REPORTS: { VIEW: BOTH, PRINT: BOTH, EXPORT: ADMIN_ONLY },
  USERS: {
    LIST: ADMIN_ONLY,
    CREATE_SUPERVISOR: ADMIN_ONLY,
    UPDATE_SUPERVISOR: ADMIN_ONLY,
    SET_SUPERVISOR_STATUS: ADMIN_ONLY,
    VIEW_OWN_PROFILE: BOTH,
  },
  DASHBOARD: { VIEW: BOTH, VIEW_SUMMARY_METRICS: BOTH, VIEW_COST_METRICS: ADMIN_ONLY },
});

export function hasPermission(role, resource, action) {
  const allowed = PERMISSIONS[resource]?.[action];
  return Array.isArray(allowed) && allowed.includes(role);
}
